# Makefile for Borland C 3.1

CC = c:\app\tc\bin\tcc
#CC = bcc

#IDIR = c:\app\tc\include;F:\puzzles\lvga
IDIR = c:\app\tc\include;C:\APP\puzzles\lvga
#IDIR = App\DJGPP\include;c:\app\tc\src\pong\lvga
#IDIR = c:\App\borlandc\include;c:\app\tc\src\pong\lvga
LDIR = c:\app\tc\lib
#LDIR = c:\App\DJGPP\lib
#LDIR = c:\App\borlandc\lib

EXEFLAGS = -O -mc -I$(IDIR) -L$(LDIR)
FLAGS = -O -mc -c -I$(IDIR) -L$(LDIR)

SOURCES = lvga\keyb.c  lvga\lvga.c lvga\ini.c lvga\mouse.c
OBJS =  keyb.obj lvga.obj ini.obj mouse.obj
EXES1 = color.exe golvga.exe mefisto.exe flood.exe colorl.exe 
#EXES2 = pongvga2.exe

#all:  $(OBJS)  golvga.exe
#all: $(test) keyb.obj lvga.obj ini.obj mouse.obj golvga.exe mefisto.exe flood.exe colorl.exe 
all: $(OBJS) $(EXES1) $(EXES2)

colorl.exe: colorl.c $(SOURCES)
        $(CC) $(EXEFLAGS) colorl.c $(OBJS)

golvga.exe: golvga.c $(SOURCES)
        $(CC) $(EXEFLAGS) golvga.c $(OBJS)

flood.exe: flood.c $(SOURCES)
        $(CC) $(EXEFLAGS) flood.c $(OBJS)

color.exe: color.c $(SOURCES)
        $(CC) $(EXEFLAGS) color.c $(OBJS)

mefisto.exe: mefisto.c $(SOURCES)
        $(CC) $(EXEFLAGS) mefisto.c $(OBJS)
		
pongvga2.exe: pongvga2.c $(SOURCES)
        $(CC) $(EXEFLAGS) pongvga2.c $(OBJS)

keyb.obj: lvga\keyb.c
        $(CC) $(FLAGS) lvga\keyb.c

mouse.obj: lvga\mouse.c
        $(CC) $(FLAGS) lvga\mouse.c

lvga.obj: lvga\lvga.c
        $(CC) $(FLAGS) lvga\lvga.c

ini.obj: lvga\ini.c
        $(CC) $(FLAGS) lvga\ini.c

clean:
        del *.obj
        del *.exe
        